[package]
name = "pkgmc"
authors = ["@h-exx"]
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
reqwest = "0.12.4"
tokio = "1.37.0"
